### Sources of Digital Data

[Marketing Data Sets](marketing_data_sets.pdf)

There are different types of data marketers and marketing analysts work with, and how these days, a lot of data is related to the use of digital media. 

We get data about different websites people visit, the way they navigate on websites, the products they purchase online, apps they download, ads they see, and so on. In order to get the most out of the data that's available to you as a marketer, **it's important to understand how this data is collected.** 

First, we'll go over how online interactions generate data. Then, we'll take a look at data collection on websites using cookies. We will also look at the use of tags or pixels. Then, we'll take a closer look at the use of software developer kits or SDKs for data collection for mobile apps. 

We'll also discuss the use of Platform APIs to help connect data that a company may already have to the advertising platforms they may want to use. Finally, we will look at the use of UIDs.

#### How Online Interactions Generate Data

To understand how data fuels digital marketing and how data and advertising are connected, it's important to have a closer look at where the data comes from.

How does that come about when you visit content online? Let's look at how interactions happen online. 

As an example, let's look at what happens when someone interacts with the publisher's website. 

Every publisher's website starts as a blank canvas made of code and stored on a web server. Think of your favorite news site, for instance. In your mind, strip away all of the content. The shell that's left is the blank canvas the website started with. 

To fill this blank canvas with content, the publisher uses a tool known as a content management system, or short: CMS. Publishers use their CMS to store, create and manage content on their websites. So, imagine your favorite news site, they use such a CMS. It's typically a system that makes it possible for many people to easily create and manage the content without needing to know how to code. 

Or in other words, it's an easy system to write a news article that you will see appear on the new site.

The publisher will leave some space on the website for `advertising.`

A separate server will place the ads. This server is referred to as the `ad server`.

So note that two different systems handle the content and the ads. The ads come from advertisers. To get the right ad in front of the right people, the publisher sends a signal to connect with the advertiser's ad server and retrieve the creative for the ad that needs to be displayed. 

Again, when we think about our favorite news website, the people who are writing the articles that you see aren't deciding on the ads that you see on the site. 

The ads you get to see are coming in from the Ad server. To publish, this website will connect with the Ad server and the Ad server fills the advertising spaces. Now let's look at what happens when someone accesses a website. 

As soon as the person's browser requests a web page from the publisher, some data about a person is sent to the publisher. That information is used to bring the right content to the person, but it's also sent to the Ad server to make sure a relevant Ad is displayed.

So, data is exchanged between the person and both the publisher and the advertisers' servers. 

The publisher and the advertiser both store data. Every interaction like accessing a page, clicking on a link, clicking on an ad or making a purchase leaves a record. The publisher and the advertiser categorize and store some of that information to personalize the content and adapt the ads people see.

So we now know that a lot of data is generated as people interact with online content. 

But what do we really mean when we talk about data? 

As you probably know, every website is made of code. That code is stored on a publisher server. Every time you interact with the website, you tell its server which piece of the code to display. Every request you make for a piece of code or elements of the website, leaves a record in the server. That record is referred to as the web server log.

A web server log consists of strings of code like this one. This code may look foreign to us but it's not too difficult to understand its components. 

First, you see a series of numbers. That's the person's `IP address`. It tells the server where to send the data. Next is a `unique identifier`. This is how the server recognizes who is asking for the information. This identifier is typically pulled from the person's browser and is usually a sequence of characters. 

Note, that this is `not personally identifiable information` also referred to as PII. 

So, no names or physical addresses are stored here. Next, if the website requires the person to log in, there may be a user name here. 

Next, there's a date and a time stamp of when the information was requested from the server. After that is the string of code that identifies what information the person is requesting. This is how the server finds the right piece of data to return. This string of code is embedded in the links on websites so that you can click on a link and give an instruction to the server at the same time.

Next, you'll see a number that tells us whether the information was successfully provided to the person. 200 means successfully delivered, while 404 means error. 

Finally, another number reflects the size of the content filed a person received. While every interaction leaves a trace in the publisher and advertiser servers, the servers often also send some information back to the user and store it in their browser as a cookie.


#### Use of Browser Cookies

Above, we saw how those interactions leave a trace in the publishers' and the advertisers' servers in the form of web server logs. But the interactions you have with websites and ads can also leave a **trace in your browser** in the form of cookies. I bet you've heard about them before, so let's explore what they are and how marketers use them. 

Web and ad servers can store some information about your interaction in a special storage area in your browser. When you interact with content from the same publisher or advertiser later, the publisher can call up the information it's stored in your browser to help it remember a few things about you and your previous interactions. So you can think of cookies as the **browser memory**, and publishers and advertisers can ask it to be reminded of relevant things.

A cookie is a formatted piece of text that gets stored in a person's browser. Cookies contain information on when the person accessed a website, saw an ad and where they clicked. Sometimes, **login information** is stored as well.

This information makes it possible for websites to remember a person's log in info for instance, remember what someone had put in a shopping cart or what content a user seemed interested in. 

Cookies allow a server to connect multiple interactions from the same person. Here's how they work. 

The person requests a page through the browser. To the server, it looks like a browser requesting a page. When the server gets this request, it sends the page the person asked for back. But alongside the page it also sends a tiny text file that's placed inside the person's browsers. The next time the person requests a page from the same server, the request will come with a cookie attached. So now the server has a little bit of information about a browser that's asking for the page.

Following is made possible through the use of cookies:
   
   * Give you locally relevant content
   * Keep you signed in on a website
   * Adjust the content you see on a site based on your preferences

In the previous lesson, we distinguished between 1st, 2nd and 3rd party data. Actually, that distinction is also very relevant when we talk about cookies, Especially 1st and 3rd party cookies. 

**First party cookies** are the text files stored in your browser by the sites that you're actually visiting. For instance when you visit your favorite news site, they will store a text file in your browser that helps this new site to remember some of your preferences. When you come back to that news site, your experience may be personalized on the basis of the information the site has stored in your browser. 

By visiting your favorite news site, you have an implicit or explicit agreement that the site can store these cookies in your browser. You've probably had to accept the use of cookies for many sites you visit. When you accept, you give the site you are on permission to add cookies to your browser. 

**Third party cookies** are text files stored in your browser by a third party with whom you don't have a direct relationship. In the case of your favorite news site, there may be an advertiser who stores some information in your browser while you visit a news site. The advertisers can do that because it has an ad showing on the news site you are visiting. For that ad to load, your browser interacts with the ad server, and the ad server can send a cookie to your browser in that interaction. But, you did not intentionally seek out a relationship with that advertiser. Hence, the cookie they store is considered a third party cookie. 

**Third party cookies** are used for tracking and advertising targeting purposes. Advertisers can use this third party cookie to build a **user profile** on you, tracking the different websites you visit and which ads you click. Thus getting a better understanding of your interests. **That understanding will help them tailor ads to you.** 

Since users have less control over 3rd party cookies and how they're used, they have raised **privacy** concerns. **Users** and **browsers** increasingly block these cookies from being stored. 

Later, we'll take a closer look at data and privacy and we will cover this in more detail. But for now it's good to keep in mind that **third party cookies are harder to rely on as they're slowly phased out as a result of these concerns.**

While cookies in general can be a great way to connect a person's interaction with the server and pass some information back and forth, they have some challenges. Ideally, the **cookie would function as the memory of the interactions between a website and a person.** 

With that memory intact, navigation would be smoother for the person. The website would know what actions they took or it might remember settings they like or pages and ads they saw, but people don't use just one browser for all their interactions with the website. 

- They may use different computers, different browsers and mobile devices. **Cookies don't work across devices and memory trace is lost.** 

- People can also **erase cookies** from their browsers, which erases the memory from the publisher and the advertiser. 

- Users can also change the privacy settings in their browsers and prevent cookies from being stored. 

- You should also keep in mind that many browsers today don't allow the use of 3rd party cookies by default. 

- One of the major complications with cookies is that **they don't work on mobile apps.** 

- As a result, it's hard for a publisher to link behavior from a person on its website to behavior on its app. 

But even with those limitations, cookies play an important role in how data is stored and used online.

If the advertiser network puts a cookie in the browser of the visitor of the website, that is considered a third-party cookie since you, as the user, don’t have a direct relationship with the advertiser network. 

[Mobile app cookies]("Mobile Tutorial Series".pdf)

#### Cookies

A "cookie" refers to a small piece of data that is stored on a user's device by a web browser. Cookies are used to track and store information about a user's online behavior and preferences. They play a significant role in digital marketing by providing insights into user interactions with websites and helping marketers deliver personalized and targeted content.

Here are key points to understand about cookies in marketing:

**User Tracking:** Cookies are commonly used to track user activities on websites. They store information such as pages visited, time spent on a site, and specific actions taken by the user. This data is valuable for marketers to analyze user behavior and make data-driven decisions.

**Personalization:** Cookies enable marketers to personalize the user experience. By tracking a user's preferences and history, websites can offer personalized content, recommendations, and advertisements. This personalization enhances user engagement and increases the likelihood of conversion.

**Ad Targeting:** Third-party cookies, in particular, are often used for online advertising purposes. Advertisers and ad networks use these cookies to track users across different websites and display targeted advertisements based on their interests and online behavior. This practice is known as behavioral targeting.

**Analytics and Measurement:** Cookies are essential for web analytics tools to gather data on website traffic, user demographics, and user interactions. Marketers use this data to measure the performance of their campaigns, understand their audience, and optimize their strategies.

**Session Management:** Cookies are also used for session management, helping websites recognize users as they navigate through different pages during a single session. This is essential for maintaining user login status, shopping cart contents, and other session-specific information.

**Consent and Privacy Concerns:** With growing concerns about online privacy, regulations such as the General Data Protection Regulation (GDPR) and the California Consumer Privacy Act (CCPA) require websites to obtain user consent before storing or accessing cookies. Marketers need to be mindful of these regulations and ensure compliance with privacy laws.

#### Tags and Pixels

**The publisher of a website can add a pixel by adding a few lines of code provided by the third party to whom the publisher wants to send data.**

There are different ways in which data is generated when people interact with content online. 

So far we looked at web server logs and cookies. Now, we're going to take a look at pixels which are sometimes also referred to as tags. 

`Pixels and tags` are used for tracking, measurement and advertising.

Let's take a look. When you have a website, you will often work with different companies to help you manage and monetize your site as well as understanding how people navigate your site. You may work with a company that helps you track user behavior on your site for instance, or companies that help you advertise your products. 

In order for these companies to help you, you need to pass some information or data to them about what's happening on your site. You, as a publisher, can see all the information in your server logs but since these other companies that help you don't have access to your servers, you need another way to give them information. 

That's where pixels or tags come in. That sounds a bit like cookies...how is this different? 

Remember that cookies are added to the user's browser after an interaction has been established. 

So, if I go to my favorite news site, I create a connection with them. Their servers send me some information and in the process of sending me that info they store some information in my browser via cookie. Advertisers that show ads on that news site can follow a similar process since their ad server will send me the ad so an interaction between my browser and the ad server is established. 

But if my favorite news site uses Google Analytics to help them track and measure behavior on the site, there isn't really any interaction that's automatically established between my browser and Google Analytics. 

Google Analytics is not sending the content or the ads, so there isn't anything I need from its servers to browse around on my favorite news site. If the news site wants to send information about my browsing, it needs to add some extra code to its site that sends data to google analytics.

That extra code that will be integrated in the site is referred to as a pixel or a tag. A pixel or tag is a small piece of code, often Javascript, that instructs the website to send some information to an identified 3rd party. As you know, a website is made up of lines of code; pixels and tags are integrated inside that code. Here is what a pixel may look like. This example is the pixel from Facebook. From the user point, this code doesn't really do anything. You don't see the pixel, in fact, it literally is a super tiny transparent square, hence it's called a pixel. When you visit a website, all the website code loads and when this piece of code loads, the transparent pixel is displayed, and the pixel is loaded. It will collect some information about the page you are on and the actions you take and send that information back to the server of the party identified in the pixel. In our example, that party would be Facebook. The information will then be used to help the website owner. In the case of the Facebook pixel, the information is used to help connect advertising on Facebook with actions taken on the site. The website owner can then check how effective advertising on Facebook was to encourage certain behaviors like purchasing or subscribing, for instance. Code in a pixel can also be used to store a cookie in the browser of the user. Pixels and tags are primarily used for tracking, measurement, and advertising purposes. Some very common examples are the Google Analytics tag, which tracks user behavior on the website and uses the data to provide publishers with insightful reports of the number of visitors, the content that's most popular, the actions taken on the site, and so on. The Facebook pixel we just referred to is another popular example. Websites that advertise on Facebook will use it to evaluate whether they're advertising results in the desired actions. They also use it to create custom target audiences: groups of people that have engaged with the website and that the publisher would like to target with very specific advertising messages.



**The Google Ads** re-marketing tag is another example. It functions similarly to **the Facebook pixel** and is used by advertisers to advertise to people who previously interacted with their site. If you are the website owner, you can integrate these pixels or tags on your webpages. The code is provided to you by the company whose pixel you are installing, so you can get a code for the Facebook pixel from Facebook. Similarly, other companies, like Google, for instance, will provide anyone who wants to install their pixels or tags with a code to do so. Usually, you can find that code in their help documentation or other help tools for developers. As a marketing analyst, you may not be the person who will be adding the pixel called to a web page, but it really helps to understand how pixels and tags work. That way you can ask the developers of the website for some help when you have data needs that require pixels or tags.


#### Software Developer Kit (SDK)s for mobile Apps

So far, we've learned about several ways in which marketers can access data related to online behavior. We talked about web server logs, cookies, pixels, and tags. 

Everything we described so far has been related to data collected from interactions with websites. As you know, a lot of the online user behavior happens on mobile devices, and a large portion of mobile activity is on apps. Apps are different from websites, and tools like cookies, pixels, and tags don't work in the same way on apps. Of course, we can still get data related to app usage, but we need to use different tools to collect the data. That's where SDKs come in. In this video, you'll learn what that's all about. 

SDK stands for Software Developer Kit. You can think of it as a toolbox for software developers. The toolbox contains code developers can install to help create applications. In some ways, you can think of it as a library of ready-made code that makes the life of the developer easier. Instead of having to manually code every piece of an app, for instance, they can plug in pieces of ready-made code from an SDK to achieve certain functions. 

Here's an example: I'm sure you've downloaded apps on your phone where you were asked to log in with your Google or Facebook account. That makes it easier on you as you don't need to create a new login. The developer of that app would have used an SDK to make that work. Instead of manually programming a way for you to log in, developers would use the Facebook SDK, which has code they can implement in their app to let you log in with your Facebook credentials. It's a bit like copying and pasting code. The code inside the Facebook SDK is especially written to make it easy for outside developers to integrate their applications with the Facebook functionality. Many platforms like Facebook provide an SDK for a number of different functions. You could use an SDK, for instance, to allow people to use certain filters in their images, or to create a smooth check-out when buying a product, and so on. SDKs exist for all kinds of software development, not just for mobile apps, but they are definitely heavily used by mobile app developers. But what does this have to do with data about user behavior? Well, when you use an SDK from an advertising platform like Facebook or Google for instance, then you'll have the option to connect data from your advertising to actions that happen in your mobile app. Imagine you have a gaming app. You may decide to use the Facebook SDK so your users can log in with their Facebook credentials. By having your users log in with their Facebook ID using the SDK, some data is sent back to Facebook. This makes it possible for you to see things like whether people who saw an ad on Facebook for your gaming app, download your app. And, you could even see whether these people are more likely to make in-app purchases, like purchasing extra powers inside your game, for instance. The code in an SDK could instruct your app to send certain information over to the platform that created the SDK. That data can then be connected to other actions marketers take using the platform, like advertising, for instance. As a marketing analyst, it's good to know that SDKs are the way to go when you need to connect marketing platforms to your app. Most likely you won't need to install any of this code yourself. But, it helps to know that you can ask your developers to build in some code that can help you track the connection between your advertising and the actions people take on your app.

#### Connecting Data Through APIs


You probably gathered from the previous videos that often, the data gathering we go through as marketing analysts has to do with connecting systems. That's because we want to measure the effectiveness of advertising along the customer journey and across platforms. Marketers want to influence behavior, but the data related to the marketing and the data related to the behavior aren't always easily connected. The marketing takes place using one system, like advertising using Google for instance. But behavior we want to influence takes place on other, a purchase on a website, an app download, a purchase in a store, and so on. Many of the systems we talked about so far will help marketers to make connections. But these systems often have dependencies that are a bit out of our control. We already saw how users can delete or block cookies, for instance. Or how browsers may prevent certain data collection. That's why we'll often rely on making more direct connections through the use of APIs. Let's explore what those are. An API or an Application Programming Interface is a tool that establishes a connection between two pieces of software. An API allows two applications to talk to each other. The API is a little bit like a courier who transports information, requests and so on from one system to another. Think of something as simple as sharing a news article on your Twitter feed. You are on the news article and you would like to share it on Twitter. An API will ensure that your request to share goes to Twitter, who will then in turn make sure the article appears on your Twitter feed. APIs really fuel our online experience today. Loads of connections are being made constantly between different websites and different systems online. How exactly does the API play a role when it comes to data? Well, APIs make it possible to share data directly with certain marketing or advertising platforms. For instance, I can use the Facebook API to directly provide Facebook with data about what happened on my website, on my app, in my stores, and so on. Why does that matter? Well, I can send data to Facebook about purchases for instance. Facebook can then help me figure out whether the ads I ran on their platform led to those purchases. I can use the API to pass on information about website purchases, but I can also pass on information from in-store purchases. Through an API, I can establish a connection and send the data that's relevant over that connection. Later in this program, we will dig deeper to see how APIs are relevant for marketers. To use an API, you would usually involve a developer who can help make the connection between your software and the software of the platform or tool you would like to connect with. Platforms like Facebook, Google, Twitter, and so on, will provide a developer with all the information and code needed to integrate the API.


APIs are an excellent tool for marketers to connect information from different platforms. They are especially powerful because they establish a direct connection between the publisher of a site or app, and the platform it wants to connect to without depending on other tools like browsers or operating systems. As a marketing analyst, using APIs to connect information from different platforms will give you more reliable information and prevent broken data connections.


#### Use of UIDs

UID stands for **Unique User ID**. It is a unique text or number string that identifies a person and it is created when the user logs in. So there are Facebook UIDs, Google UIDs and many others. There are also device IDs associating a unique person with a device like a phone, for instance. When you create an account on an online platform like Facebook, Google, Amazon and so on. You provide them with some information and you create a log in, a user ID, and a password. Let's say you create an account with Google for example. Google will create a text or number string to associate with your unique account and link that string to the information you provided. This text or number string is your unique ID, in this case your Google ID and it will help the company associate data with your account. Now, no matter through which browser or device you access Google, all your behavior can be associated with that ID as long as you're logged in. That's super helpful as it enables the platform, in this case Google, to connect what you do on your computer with your usage on mobile for instance. So anywhere you use your Google log in, your behavior can be stored and linked to your Google ID. For publishers or platforms that use UIDs, it helps them to overcome some of the challenges they face when they use cookies. Remember that cookies are stored in the browser but sometimes people use different browsers or they access a site on a computer and later again on a mobile phone, for instance. The UID makes it possible for publishers to link behavior from a person on different browsers and on apps so that it's possible to get a clearer and more complete picture of the users across platforms. With a UID, interests, behaviors, demographics and other information can be stored. Anytime a person logs in, behaviors can be associated with them. In the introduction to this video, I also refer to device IDs. These are also important for marketers. In both iOS and android, an ID is stored in the settings of the device and that ID can be accessed by advertisers if the user allows it. When users interact with advertising in an app and they have opted in to share their device ID with advertisers, it makes it possible for the advertisers to advertise to you across different apps. That way, they can show ads and track behavior on one app, like Instagram for instance, and then use that information to advertise to you while you're using a different app. This type of tracking used to be a default setting in most phones. Nowadays, apps on Apple devices have to prompt their users to ask for permission to track their behavior and use that data across apps. You may have seen this message pop up on your phone when you are opening an app. It specifically asks you whether you are okay with this app tracking you and sharing your data with advertisers. This is a recent effort by Apple to protect users' privacy. It's important to note that UIDs use a number or text file, but they don't store personally identifiable information. Personally identifiable information is any information that would help someone to identify a person, like your name for instance. You will hear marketers also refer to this as PII. Actually these days, most companies go through a lot of efforts to protect your personal data. Companies that work with online data will often use data hashing for that. In data hashing, the original data item gets translated into a hashed data item by applying an algorithm. As a result, what's stored is unrecognizable unless you have the hashing key, another algorithm that lets you reverse the data back to its original form. This is an extra safety measure to help keep people's privacy intact. Now you know the main ways in which behavioral data is collected online. We looked at web server logs, cookies, pixels or tags, SDKs and APIs. And now you also understand what UIDs are. That was a lot to cover, and these concepts can be a bit confusing at times. Don't worry. We'll repeat them again in other parts of the program and gradually their different applications will become increasingly clear. In the next lesson, we'll go through an example of how a company might use all of these different ways to collect data. It's a good opportunity to further practice these concepts. I'll see you there.

