
# Marketing Analytics Foundation 

<style> 
body {text-align: justify} 
</style>

## Definitions

**Retail Media**

Retail media refers to advertising and promotional activities that take place within retail environments, both online and offline. It involves brands and advertisers collaborating with retailers to reach their target audience directly through various advertising channels within the retail space. The goal is to influence consumer behavior, drive sales, and enhance brand visibility at the point of purchase.

In the context of e-commerce, retail media often involves advertising on the websites or platforms of online retailers. Brands may pay for sponsored product listings, display ads, or other promotional placements on these platforms to increase their products' visibility to potential customers.

In physical retail settings, retail media can include in-store displays, product placements, and other advertising methods within brick-and-mortar stores. This form of advertising is designed to capture the attention of shoppers while they are in the process of making purchasing decisions.

Overall, retail media aims to leverage the retail environment to deliver targeted and relevant advertising messages to consumers, ultimately driving sales and creating a mutually beneficial relationship between brands and retailers.


## Introduction to Marketing Analytics

### Some Marketing terms


#### A brick-and-mortar store 

It refers to a physical retail location where business is conducted in person with customers. The term "brick-and-mortar" is used to distinguish these traditional stores from online or e-commerce businesses. In a brick-and-mortar store, customers can visit the physical location, browse products on shelves or displays, make purchases in person, and interact with store staff.

The term "brick-and-mortar" comes from the materials used to build physical structures—bricks and mortar. This contrasts with online or virtual stores, which operate on the internet without a physical presence. Brick-and-mortar stores have been a common and traditional way of conducting retail business for many years, but the rise of e-commerce has led to increased competition and changes in the retail landscape. Some businesses also use a combination of both brick-and-mortar and online channels, known as `omnichannel` retailing, to reach a broader customer base.

#### Retail Media

"Retail media" refers to the use of media channels, often within a retail environment, to promote and advertise products or services. It involves advertising and marketing efforts directly within the retail space, whether in physical stores or online platforms.

In a retail media strategy, businesses leverage various channels such as in-store displays, digital signage, sponsored product listings on e-commerce websites, and other promotional methods to reach their target audience. This approach allows retailers to monetize their own media properties and engage with customers in a more targeted and contextually relevant manner.

The concept of retail media has become increasingly important as e-commerce and digital marketing have grown in prominence. It provides retailers with an additional revenue stream and allows brands to connect with consumers at key points in the purchasing process.

For example, a **retail media strategy** in an online marketplace might involve brands paying to have their products featured prominently in search results or on category pages, increasing visibility and potentially influencing purchasing decisions.

### Role of marketer

If you spend some time online, you've probably noticed that quite a few of the **ads** you see are for products you're genuinely interested in and some of these ads may have prompted you to buy.  Well, that's no coincidence. **You likely saw these ads because some underlying data and marketing analysis made the advertiser understand that you might be interested in the product advertised.**   

That's just one of the many ways in which marketing analytics powers marketing. In fact, it's fair to say that all marketing benefits from `data` and `analytics.` 

Marketing is responsible for promoting and selling the products that a company makes. And that usually involves the following steps: 
First, the marketers identify the `right customers` for the product. `They think about and research who might be interested in buying the product.` They may interview people and use questionnaires to understand their **needs** better and whether these needs might be met by the product they sell. 

They will also try to form a better picture of the lives of the people that may want their product. All this is referred to as `market` or `consumer research` and it's an important part of marketing. Marketing analytics is essential in this phase to help analyze the data from the research. Based on this research, marketers will create a message and a story about the products they sell. They will also decide where that message should go so it can reach the customers who may be interested. This may mean creating a website, a Facebook page, or an Instagram account. 
And in some cases, creating ads that could be put in magazines, on TV, on the web, and so on. This is the creative part of the marketer's job. 

Many companies will rely on advertising or creative agencies to help them. Coming up with the right message and the right imagery to complement that message is a real art. But marketing analytics is used in this phase as well. 

Often `marketers will test their messages out and gather data about the ads or promotions they run to try and understand what works best for their audience.` To get marketing messages out, marketers need a plan. Marketers will carefully select the different places where they talk about their product. 

And if they plan to advertise, they will work on strategies that help them to most effectively spend their advertising budgets. Marketing analysts have an important role to play here. By using data and analytics to create their plan, marketers can save time and money. 

Once campaigns and promotions start to run, marketers will watch them carefully and focus on evaluating the results they see, like clicks on ads from campaigns, sales resulting from ads, and so on. Based on that information, marketers will adapt their advertising and their marketing plans. Given that a large share of marketing budget is spent online these days, `real-time updates are possible` and good marketers will make use of the opportunity by optimizing in real-time as well. But to do it effectively, they need marketing analytics. 

After an advertising campaign runs its course, marketers will want to evaluate whether their money was well spent. And they will have to report back to other people in the business on the success of their efforts, so they perform more analysis. And while reporting is essential, this analysis will also help the marketer get better and optimize their message and strategy for their next campaign.The better you are at marketing analytics, the better you'll be able to optimize and get your message out to the right people in a more efficient way.   

Analytics plays a crucial role in marketing. A marketer equipped with good data and analytics, will be a better marketer. Online actions generate loads of data that can be a goldmine for marketers if used well. As a result, marketing analytics skills are in high demand, and all great marketers today rely on analytics to make decisions. 

### What is marketing analytics? 

It is the practice of measuring and analyzing data to inform, evaluate, and improve the performance of your marketing initiatives. Marketing analytics is all about gathering and analyzing data to make your marketing better. 

5 Main Uses of Marketing Analytics

1.	 Identifying the target audience
2.	 Planning and forecasting
3.	 Evaluate marketing effectiveness
4.	 Marketing optimization
5.	 Optimizing the sales funnel

Now let's take a look at where the role of the marketing analyst comes in, or how marketing analytics can support and improve marketing. 

**1. Identifying the target audience:** Marketers have limited budgets, so they want to make sure that their marketing message reaches a `receptive` audience. Or in other words, they want to talk to people that may have an interest in buying their product. In marketing, they refer to that as your target audience. So how do marketers find that audience? Well, they use research. 
Imagine a marketer for a mattress company. They could use surveys to get a better understanding of when people buy mattresses, what they find important when buying a mattress, how much they would spend on a mattress, and so on. They might also use some databases that exist about mattress sales, and the demographics of the people who buy them. All of this will help describe who the best target audience is for the mattresses.    

- What are their characteristics?   
- Where do they live? 
- What phase of their life are they in, and so on? 

All the information the marketer gathers comes in the form of data. And marketing analytics will help to make sense of that data and paint the detailed picture of the target audience the marketer needs to create the marketing message and get in front of the interested people. 

**2. Planning and forecasting:**  Marketing and advertising can be expensive. So before marketers spend their budgets, they evaluate where and when they should put their marketing message. They will carefully think about how much of their time and how much of their budgets should be spent on social media, ads on TV, radio, search engines, and so on. Often, marketers will take a look back at their previous marketing efforts, and on the basis of the success they have had with campaigns in all of these different places, they may decide to spend more or less money in some of them this time around.    

The mattress company may use data from the previous year to determine the mix of advertising for the coming year. They may have learned, for instance, that advertising on TV and social media really worked for them, but that there was little payoff from the ads on the radio. Often, this exercise comes with a detailed forecast of the sales they can expect based on the budget they plan to spend. This is where marketing analytics comes in. The more a marketer can rely on data and analysis in this phase, the better the results of their marketing will be. After marketing campaign is over, marketers will take a look back and ask themselves whether their campaign was effective. It helps them to learn more about what worked and what didn't work. But they're also doing it to report back to other people in the company.   

**3. Evaluate marketing effectiveness:**  They're given a budget, and management typically expects a report on how the budget was spent and how successful the marketing was. For our mattress marketer, there may be a quarterly management meeting in which the marketer reports the sales that resulted from the marketing campaign. The marketer may also use this opportunity to show data on the ads that worked best, the placement of these ads that generated the largest audience and sales, and so on.     


Showing that the marketing was effective is crucial for most marketers, as it will help them to get the budget they need for success in the future. 

**4. Marketing optimization:** Even after very careful planning and forecasting, things can always be improved. This is true with marketing too. Once a marketing campaign is up and running and you collect or gather data on how it is performing, there is an opportunity to optimize. And the more data you have, and the more you know about analytics, the better you'll be able to fine-tune and optimize your marketing. As soon as you get some information on how your ads are performing, you can use that information to adjust your marketing. 

Say for our mattress company, if you learn from the initial data that certain search engine ads are delivering more sales than others, you could decide to spend a bit more money on the ads that perform well, and less on the ads that don't. If you can take these kinds of actions, you optimize how your money is spent. Data and analytics are really powerful that way, and can save you quite a bit of money. 

**5. Optimizing the sales funnel:** Finally, there's a specific task of making sure that people who want to purchase a product or have shown an interest can easily do so. Marketers will refer to that as optimizing the sales funnel. That is because they think of the sales process in a few steps. For instance, you could think of the sales process in four steps. 

**Awareness** – **Interest** – **Decision** – **Action**   

Awareness; or when a person first hears about a product. Then Interest; which is when a person is interested in the product and may try to learn a bit more about it. Then there is the Decision step when a person decides that they want to get your product. And then there is the Action step, when they buy your product.   

Marketers described this process as a funnel, because as people go through this process, some people drop-off and don't take the next step. So when you draw the group of people that go through the four steps, the groups get gradually smaller. 

And when you put these groups together, it looks like a funnel. When marketers talk about optimizing the funnel, they really talk about reducing the number of people that drop out. 

Say for our mattress marketer, it's important that as many people as possible who are aware of the mattress become interested. And of the people who are interested, you want as many as possible to decide that they want your mattress. And then you want them to take action and buy your mattress. Since the marketer spends money on getting people to consider the mattress, they want as many people as possible to take all four steps and check out. 

Data and analytics will help inform marketers about how healthy their sales funnel is, how many people drop out and don't take the next step, and why that may be. 

### The Future of Marketing is Data

The future of marketing will be defined by analytics. Marketers must use data to more accurately understand who their customer is and predict what their future behavior will be.

Marketing is all about personal connection. `It's about filling a need or desire a customer has with a product or service you offer, and providing value to that customer while doing so.` 

Marketing connects people with a problem they want solved to the business that can solve it. But too often, companies are simply guessing at who may need their product or service, and may advertise the features of their products without articulating any of the benefits to their customer. Or, they may just assume that everyone will want their product and never put the effort into identifying a target audience of those who will not only benefit from the product or service they offer, but who can become brand ambassadors in the future. 

Additionally, consumers today expect personalized experiences with the brands they interact with, from unique online and brick-and-mortar experiences, to customized product offerings, to a personable voice on social media. Just as a blanket advertising approach doesn't work for organizations, a one-size-fits-all experience doesn't work for customers.

But marketers don't just need better awareness about making personal connections with their audience, they need tools to do it as well. **There's a shift in looking at how well each product performs to how valuable each customer is**, and marketers can only get to know their customer and create that personal connection with data. 

With data, marketers can learn:   
- what products each customer has bought in the past       
- what social media content is resulting in the most purchases          
- what keywords customers are searching for     
- age, gender, and location     
- what their interests are      
- how to market to those customer in the future       
 
This is why the future of marketing will be defined by analytics, or using data in order to more accurately understand who the customer is, what their past behavior has been, and what their future behavior will be. The future of business growth and success will belong to organizations who will use data in smart, insightful, applicable ways.

### Marketing Trends for a Data-Driven Future

As we see an increase in data-driven customer connections, here are some trends we'll see in the future of marketing.

**Smarter use of data**   

Marketing teams will increase their use of data in order to learn more about their customers, which will create better targeting, personalization, and connection. More personalized marketing means more returns, as 80% of consumers say they'd be more likely to purchase from a brand that offers personalized experiences, and 72% say they only engage with marketing messages that are specific to their interests.

**Growth of AI** 

There will be an increase in use of AI, machine learning, and algorithms in marketing, as it can predict patterns and make recommendations based on the insights it sees. Already, algorithms choose 70% of what viewers watch on YouTube and 75% of what viewers watch on Netflix, and recommendation algorithms drive 35% of sales on Amazon. Additionally, automation will increase as well, with Gartner predicting that "By 2023, autonomous marketing systems will issue 55% of multichannel marketing messages based on marketer criteria and real-time consumer behavior, resulting in a 25% increase in response rates."

**Shift to first-party data** 

As Google is phasing out its use of cookies, organizations will shift from third-party data to first- and second-party data, which will help them understand their customer more precisely.   

Giving customers transparency into how data is collected will be a priority as well. According to Kevin Cochrane, the CMO of SAP Customer Experience, "*To initiate a more trustworthy relationship, organizations must start by eliminating internal processes of acquiring third-party data. They must use only data that they have earned through explicit customer consent. ... Moving forward, consumers should (and will) have full visibility into how extensively their personal data is being monetized.*"    

**More online data**  

As the COVID-19 pandemic shifted life online, organizations suddenly saw an increase in new data they could collect about their customers, and the trend will only increase. "In the absence of the face-to-face, we had to lean in on digital, and that allowed us to have the information, the data, to then better serve our customers," notes Kevin Warren, CMO of UPS. "This year really has revealed that strategic importance of analytics that maybe wasn't quite there pre-COVID." 

**Better budget optimization** 

As marketing teams are able to better target their customers, they'll be able to better optimize their budgets. In wanting to optimize its marketing budget, `DoorDash first looked at which ads brought in new customers`, drew channel-level cost curves based on the data, and created better ways to deliver. "Accurate, timely, and fine-grained attribution data is the key to understanding and optimizing our marketing," they explain.


### An Application

We are going to refer to an imaginary company, DCB Cleaning Services. They are a company that provides office cleaning services in the San Francisco Bay Area. James manages marketing for the company. Recently he presented an idea for a new product to his management, Snackwall. It's a service where the company installs a snack wall in an office. Customers subscribe to the service and select their snacks and refills through an app. Management was very excited about his idea and developed the product. James was given a marketing budget to launch the new service. We'll follow James and look at some of the decisions he needs to make.

#### Audience

James at DCB Cleaning is excited to bring Snackwall to market and he's gearing up to launch. With a quickly approaching launch date and limited budget, James knows that it is essential to get the message about Snackwall in front of the **right audience;** people who may be interested in the service. Given his limited budget, he wants to make sure not to waste any of his money on people in offices where Snackwall would likely not be a good fit. 

James needs to define his target audience. James believes that it will be best to promote Snackwall among the **existing** DCB Cleaning clients. But he does not think all the clients will be interested. 

To get a better understanding of who may have an interest, James decides to create a **survey.** He divides his survey in three parts. 

In the 1st part, he asks questions about the office space.     
- How many people work in the office? \
- Is most of the work desk work? \
- Where's the office located? \
- How far is the office from the convenience stores? \
- Does the office provide lunch, etc.? \

In the 2nd part, James asks about the employees and the work they do.   
- What is the average age of the employees at the location?\
- What's the education level?\
- What industry is the company in?  
   
In the final part of the questionnaire, James describes Snackwall and asks the level of interest in the product, from not at all interested to very interested. James' survey goes out to all 300 clients of DCB Cleaning. It's an online survey and 200 clients fill it out. Now that James has the answers to his questions, he goes to his marketing analyst, Alia, who had suggested to survey in the first place and who will help James analyze the results. Alia sorts all the responses in a spreadsheet. Then, she runs the segmentation analysis on the data. Segmentation is a technique we will learn more about later in this program. It's a way to sort people in groups based on characteristics they have in common. In this case, Alia uses segmentation to get a better understanding of the characteristics that people who are interested in Snackwall have in common. After Alia runs her analysis, she finds that there are two distinct groups that have a very high interest in Snackwall. She presents her results to James. The 1st group she named "Focused Tech". This group includes companies that have over 30 employees, provide lunch on-site, are active in the tech industry, and are primarily employing engineers and have a young workforce. The 2nd group Alia refers to as "Isolated Office". This group includes companies with between 30 and 50 employees located outside of the urban areas with little access to food. They don't provide lunch for their workers. They are in various industries and their workforce is young. Alia also tells James that the Focused Tech segment is quite a bit larger than the Isolated Office group. This information is super helpful for James. Using the information provided in the survey responses, James does a bit more work on describing these two audience groups. He plans to target his first advertising campaign to the Focused Tech audience. He will advertise to his current clients, but he will also use this information to find more companies that are similar to the audience in the Focused Tech segment.


The segmentation that James' marketing analyst Alia did for him helped James define his target audience. He knows that narrowing his advertising to this target audience will help him spend his budget wisely since it will increase the chance that his ads will be seen by people who are interested in his product. For any marketer who's trying to define their target audience, marketing analytics is crucial.


Segmentation helps to group the people interested in Snackwall and describe their common characteristics 


#### Planning and Forecasting

A second crucial task where marketing analytics supports marketing is in the planning and forecasting phase. James has a budget that he can use to market Snackwall. He has identified a target audience, but now he needs to come up with a marketing plan. He needs to make sure that he makes the best possible use of his budget. On top of that, his management would like to get a sense of the expected sales. There are a few things James needs to consider in his plan. First, he needs to select the platforms he will use to advertise. James believes that social media would be great, but he needs to decide which platforms to include. Alia, who runs marketing analytics for DCB cleaning and the Snack Wall product, has access to comScore data, a database with information about the different online media people use, people's browsing behavior and demographics. Alia shows James how the age group of the focused text segment he is targeting uses Facebook and LinkedIn a lot, more so than Instagram, for instance. James agrees that these would be good platforms for his ads. Now he needs to decide how much of his money should be spent in each platform, should it be 50-50? Alia advises against that. She shows James how based on the company's advertising experience, they found that Facebook tends to be cheaper if you target your ads well, or in other words, if you put the right message in front of the right people. But she has also found that LinkedIn helps to generate awareness among professionals. Even if they see less sales coming from the ads directly, they tend to create good leads. Based on this historical information, Alia has created a formula that she can use to help James divide up his budget. James ends up putting 70 percent of his ad budget in Facebook and 30 percent in LinkedIn. Now, James has one more step to take. He needs to present his plan to his management and his boss expects to see a forecast of the sales. Alia suggests that James rely on the historical data they have about the results of the campaigns the company ran for its cleaning services. They both know that this product is different, but since the product is new, this is the best data they have. Alia shows James how she can use the data to predict the number of people that will click on his ads in Facebook, and how many of those people will then go on to subscribe to the service. She can do the same for LinkedIn. This sounds simple enough, but in fact, the model Alia uses to forecast is a bit more complex. It also involves factors like the types of ads James is planning to use, how many video ads, single image ads, etc. The time of year when the campaign will run to people, James will target and so on. All of this information helps Alia build a better model to help James forecast the sales for Snack Wall.


As you can see from this example, data and analytics play an important role into planning and forecasting phase. Of course, James could decide how to spend his budget without using analytics, but the more data and information James uses to plan, the better his strategy will be. Alia used what a company learned from the past, and that helps James to build his marketing approach and forecast sales. If you don't have data from the past that can help guide you, marketing analytics will often use data they can purchase, like the comScore data about browsing behavior we referred to. In any case, using marketing analytics will make your strategy and forecasts better.



Historical data for similar events in the past can help predict events in the future and can thus guide the planning process


#### Evaluate Advertising Effectiveness


Marketing analysts play an important role in helping to evaluate marketing effectiveness. Or another way to think about this is whether or not the marketing budget was spent well. And an important part of that is evaluating the effectiveness of advertising. 

Marketing analysts will try to answer the question: did the advertising campaign payoff? A good starting point to answer that question is by looking at `return on Ad spent or ROAS.` **ROAS** is simply a way to find out how much `revenue` you made on your advertising versus what you spent on it. The calculation for ROAS is revenue made from the ads divided by advertising costs of those ads. For example, if you spent $1 on advertising and made $10 off of that advertising, your ROAS as is 10. 
Or can be expressed as 10 to 1 or 10x. So this advertising made 10 times what we spent on it, which would be pretty good.


Marketing analysts will use ROAS to compare how ads on different platforms perform. Or they may use it to compare campaigns they ran in the past with new campaigns and so on. All of this will help them evaluate whether they are getting the most for the advertising dollars they're spending. Or whether there is room for improvement. Let's go back again to James and his campaigns for SnackWall. After is campaign ran for two weeks, he finds that ROAS on his facebook ads is 12. This means that for every dollar he spends on advertising on Facebook, he sees 12 dollars in revenue for the Snack Wall product. That doesn't sound too bad. But James knows that the advertising campaigns he ran on facebook in the past for the cleaning service had a ROAS of 23. So now James is a bit worried, he doesn't think that the product is less attractive, but he thinks he could optimize his campaign. He decides to create new ads with more images and a clearer explanation of the service. Two weeks later, James sees that ROAS for his ads is up to 19. James feels a lot better about that. He thinks there's still some room for improvement, but this is definitely going in the right direction. Marketing analysts will use different data and tools to calculate ROAS. Most advertising platforms provide detailed reports to calculate and track the effectiveness of ads. Of course, the example we walked through here is a bit simpler than what analysts encounter in real life, as there are a few more considerations that go into evaluating the effectiveness of ads. In this program, we will cover several techniques that you can use to evaluate whether your campaigns paid off. As you'll find throughout these courses, ad effectiveness evaluation is a crucial task for marketing analysts


#### Optimize your Marketing Strategy

We discussed that a lot of planning goes into marketing from identifying the right audience, to creating the right message, to selecting the right channels for that message. But once you actually start your marketing, you get a lot more data that provides you with helpful information that you can use to adjust your plan and further optimize. 


Actually I find that that's the beauty of digital marketing in particular, as soon as you start running campaigns online, you get data. And you can use that data to change course and adjust in real time. That's super powerful especially if you know marketing analytics. Here are some of the things marketing analytics can help with when it comes to optimizing your marketing campaigns.     

* First, if you're running ads in different channels like Facebook, YouTube, Twitter, Google, and so on, you may find that as the initial data on the effectiveness of your ads come back that some of the ads work better than others. Some channels may be more effective for your message and for your target audience than others. That insight can help you adjust your marketing mix. You may decide to shift some of your remaining budget to the channels that perform best. 

* Second, you may see that within a channel your ads aren't exactly delivering the results you were expecting. That may prompt you to change your advertising a bit or in other words, optimize within a channel. You could change your message or the ad creative you're using or you may adjust who you're targeting your ads to, in other words, the audience that will get to see your ad. 

* And third, while you make these changes in your ad strategy, you may decide to test your new ads or the new audience that you will target. You can do that by running your new ads as well as the initial ads and test them against one another. That way, you can see whether your new ad does indeed work better than the old ad. Testing is a powerful way to make your decision and adapt your marketing based on data rather than intuition. Let's go back to James. Remember how Alia had suggested, based on historical data, that he put 70% of his budget in Facebook ads and 30% in LinkedIn. Well, after the ads ran for two weeks, James noticed that he got better results from LinkedIn than he and Alia expected. So, he decided to put a little bit of the Facebook budget into LinkedIn instead. And when James saw that the ads in Facebook did deliver less results than he had hoped for in the first three weeks, he decided to change the ads to include a clearer message and more images. However, instead of just stopping the first campaign altogether and switching to these new ads, James decided to run both ads and see which one delivered the best results. Based on the data, he learned that the new ad with a clearer message and more images was the better one. So he decided to put all his Facebook budget towards this new ad and stop the old version from running. This type of fine tuning your marketing strategy based on data can have huge payoffs. It helps you to get the most results for your budget. And that can mean big savings and a big difference in the payoff from your marketing. Because a larger share of the marketing budgets these days is spent on digital marketing, and because digital marketing makes this type of optimization possible, marketing analytics has become increasingly important over the past decade. Businesses have learned that if you let the data speak, you get a lot more out of the marketing budget.

#### Optimize the Sales Funnel

 We discussed how marketers will pay close attention to the sales funnel and how they might split the purchase process in four different steps; 
 
* awareness,    
* interest,   
* decision,   
* and action.   

As you can imagine, getting people to the awareness stage usually involves quite a bit of time and effort and often budget. If you are introducing a new product, for instance, you need to get a word out to an audience that may have an interest in your product. Often that involves developing an ad, buying advertising space, and so on. It's no wonder then that marketers want to closely study what happens next. That's where marketing analytics comes in to help them understand if and how people make it through the sales funnel. Specifically, they want to identify points of friction or points where people stop moving or leave the funnel altogether. Friction can happen at different points of the funnel. For instance, people may be aware of your product, but it may be hard to get them to become interested. That could happen if you just don't get your message across or don't explain the benefits of your product very well. That may mean you have to change your advertising message. You may also find that people who have become interested don't bite the bullet and decide to buy your product. That could be because a competitor may have a more attractive offer, or they may have a better message and people may decide to buy their product instead. In some cases, you may see people who've decided to get your product, but they failed to take action, and that could be because there's friction in the checkout process for instance, like on a website that's hard to navigate or that does not work well on a mobile phone. By studying the data on the number of people that make it from one stage to the next, or by evaluating the flow of how people navigate your website, these points of friction come to light and that's what shows a marketer where they should focus their efforts and adjust their marketing strategy, or in some cases, parts of the product or the sales process.

Indeed, anything that hampers the online checkout process or leaves the user with questions during the process can cause friction. 

When James was evaluating the sales funnel for SnackWall, he saw that there was a substantial drop-off from the decision to the action phase. Of the people that made it to the SnackWall website, only 11 percent ended up enrolling and thus purchasing the product. While James figures that some drop-off is natural, he and Aaliyah did a little bit more digging. In fact, they turned to Google Analytics and evaluated how people flow through the different pages in the online checkout process. This is the type of report they were studying. We will learn more about these reports and Google Analytics later in this program. They saw that people who landed on the website did click on the "Enroll Now" button, but they did not submit their information when they landed on the next page. This puzzled James and Aaliyah and they decided to interview a few target customers. They interviewed five people and had them go through the checkout process with them. As they were going through the website, all five of them told James and Aaliyah that they did not feel comfortable providing their name and company information without a clear idea about what a SnackWall subscription would cost them. As a result, James and Aaliyah created a quick cost calculator. Instead of the "Enroll Now" button, they now have a "Learn More" button. That leads people to a page where they are asked how many employees they have and they get a quick calculation of the estimated costs of the SnackWall subscription. Then there is an "Enroll Now" button. After making this change to the website, James saw the enrollment percentage go up to 20 percent. As I'm sure you can imagine, James was glad he did some digging into the sales funnel data. Analyzing the sales funnel can highlight weak links in your sales and marketing process and give you clues as to what part of the process may warrant more research and where there may be opportunities for optimization.


#### Discussion: Friction in the purchase funnel

While browsing online or on social media have you noticed an ad campaign that caused too much friction and resulted in you abandoning the sales funnel. 

Was it an aspect of the campaign that caused you to lose interest? If so, describe what caused you to lose interest.

Did a competitor have a better offer or perhaps a better message? Who and why?

Was their website difficult to navigate? If so, describe what made it difficult. 








