### Collecting Data for Marketing: Application


#### Intro

We have looked at web server logs, cookies, tags or pixels, SDKs, APIs and we have also talked about UIDs.

Each of these methods can help you achieve slightly different things and I think they can be quite confusing. To do that, we're going to take a look at another fictitious company, Calla & Ivy. Calla & Ivy is a flower shop in Amsterdam; Imra is the owner of the store. She always loved fresh flowers, but she is particularly known for her handbound bouquets. A few years ago Imra started selling these bouquets online and her business has expanded quite a bit as a result. She now employs a few people who help her focus on the website and they also help her with her marketing. Recently, Imra introduced a flower subscription service. Subscribers can schedule monthly deliveries of bouquets to their home. In the next video, we'll explore how Imra and her team collect and use data to help them market their products. 

#### Collecting Data

There are different ways in which data is collected online. Different methods serve different purposes. And in this video we'll walk through an example of how these different methods can be used in a real life scenario. 

For the scenario, I'll refer to our florist in Amsterdam, Calla & Ivy. Imra, the owner of Calla & Ivy, is introducing a new product, a flower subscription. People can subscribe on the website or on the Calla & Ivy app to receive a flower delivery every month. It's a way for people to get the fresh flower bouquets Imra is known for delivered on a regular basis and add some seasonal color to their homes. As the first step in making the product available, Imra and her team created a landing page on the Calla & Ivy website where they explain what is included in the subscription and where people can enroll.


When people click to enroll, they provide all their details for shipping and payment. It's important to Imra and her team to track the appeal of this new product. She wants to know how many people check out the landing page and how many people subscribe.

In theory, she could get this information from her web server logs. Remember, the web server logs keep track of all the interactions between people and the website. But in practice accessing and going through those logs it's not easy or practical. Instead, the team at Calla & Ivy tracks website traffic and website behavior using Google Analytics. 

For Imra and her team to use Google Analytics to see the interaction of people on their website, they first need to add the Google Analytics tag to the website. This tag or pixel is a piece of code that gets added to every page of the Calla & Ivy website, which sends information over to Google Analytics. The information sent by the tag includes things like how many times the landing page for the subscription service was viewed, how many people clicked on the subscription button, how many people filled out the subscription information and so on. 

Google Analytics sorts all this information in neat reports that help Imra to understand whether the new product is a success and whether its popularity is growing. From studying the Google Analytics reports, Imra learns that many people visit a landing page but far fewer subscribe. 

After discussing this with her team, they decide that it may be a good idea to present people who hesitate with a coupon on their next visit, making their first bouquet free when they subscribe. To make this work, Imra decides to use a cookie. 

Now, when people access the Calla & Ivy website, a cookie or a piece of formatted text, is added to their browser. It stores information about a user's visit to the site and it stores whether people accessed the page that describes the subscription. Now, when people leave the site and come back at a later point, the cookie will help recall that this person had already been to the site and had shown an interest in the subscription. If that is the case, a large overlay with the coupon comes up on the page the user is visiting, encouraging them to subscribe and get the free bouquet. 

Calla and Ivy also has an app that makes it easy for people to order flowers or subscribe, monitor and manage their subscription. Of course, Imra wants to understand the behavior of people that use the app as well. So, her team installed the Google Analytics SDK. 

Remember that an SDK or software developer kit is a library of different pieces of code that you can integrate in your app to make certain functions possible. By installing the Google Analytics SDK, the interactions of people with the app can be sent to Google Analytics so Imra can get a full picture of all the online usage, whether on the app or on the website. On the website, she can use the Google Analytics tag, but on the app that doesn't work, hence the SDK. 

For those people who live in Amsterdam, there's a good chance that they dropped by Imra's physical store to buy flowers. In some cases, people may learn about some of the new seasonal bouquets from ads the marketing team is running on Instagram. Instead of clicking on the ads to buy online, they decide to buy the flowers in person. Imra's marketing team is eager to connect the dots here. They would really like to know how effective their ads on Instagram are and they want to count all the resulting purchases, not just the purchases that happened online. That's where the marketing team relies on an API, or a system that lets them connect two pieces of software. 

In this case, they connect their in-store customer management software to the Facebook API. That way, every time a purchase is made in-store, data can be sent to Facebook. Based on some information that may be known about the purchaser, like the email address for instance, it may be possible to link the purchaser to a known Facebook user Id. Imra's team can then assess whether the purchaser saw an Instagram ad and may thus have been influenced by that ad to make a purchase. This information is important to the marketing team to have access to, so they are able to better understand their ads' effectiveness.

This is just a brief view into what may go on in a company and its marketing department on a daily basis. And as you can see, data plays a crucial role in many tasks that get executed on a regular basis. Marketers rely on different methods to get to the data they need.

#### Implementing the Facebook Pixel, SDK and API

**Implementing Data Collection Tools**

In previous lessons, we’ve learned about the many different types of data that can be collected, from the different websites people visit to the ads they see along the way. Just like there are many different data points, there are various ways to collect data, each with their own features and purposes. Although much of the information these tools collect and organize for you can be found on the web server logs for your site, that’s not always easy or practical. In this reading, we’ll take a look at three tools that will help you collect data. 

**Facebook Pixel**

Pixels, also referred to as tags, are used for tracking, measurement and advertising. As mentioned in the introduction section above, it’s not always easy or practical to look at data from your web server logs or even cookies. Luckily you can work with companies to help you track user behavior or advertise products. A pixel is a small piece of code that you can add to your website that  instructs it to send some information to an identified third party, in other words, these companies looking to help you utilize your data. The Facebook pixel is one example. Here, the information is used to help connect advertising on Facebook with actions taken on the site, allowing you to check how effective your advertising on Facebook was. 

**SDKs**

An SDK, or software development kit, is a library of pieces of code that you can integrate into your app to add certain functions. Where on a website you can use a pixel or tag, you would use an SDK for your app. The SDK sends the information about people’s interaction with the app to, for example, Google Analytics where both website and app information can be aggregated. A great example of an SDK that you might see every day is an app that asks you to sign in with your Google or Facebook account. For your website, you might use an SDK to create a smooth checkout experience for customers, as well as, of course, tracking various data points of your browsers’ activity. If users have signed into your app using their Facebook account, for instance, you can also see whether an ad they saw on Facebook inspired them to download your app and make in-app purchases. 

**APIs**

An API, or an application programming interface, is a tool that establishes a connection between two pieces of software. Remember the example of sharing a news article on Twitter from the previous lesson? In the same way APIs make it possible to share your article, they make it possible to share data directly with certain marketing or advertising platforms. This is useful because you can then use these connections to learn more about the results of your marketing activities. For example, you can send purchase data to Facebook, which can then help you figure out whether the ads you placed on their platform lead to the purchases. 

**Implementing the tools**

How to do it

Using these tools is often as easy as integrating them into your website’s already existing code. Most of these tools, for example the Facebook pixel and the Google Ads Remarketing, have the code readily available in the help documentation or other information for web developers. This allows you or your content developers to install the code easily so you can start tracking.

Why they’re useful

Implementing tools such as these can allow you to encourage browsers of your website and app to purchase, subscribe and more. The Facebook pixel, for example, can also create custom target audiences consisting of people who have engaged with the website and who you would like to target with more specific advertising messages. 

These tools also allow you to integrate your website experience with that of your app. For example, you can use an SDK to instruct your app to send certain information over to the platform that created the SDK, and that data can then be connected to other actions marketers take using the platform, like advertising.

#### Review

First, you learned about different sources of data marketers use. You now know that marketers use both offline and online data. And you also understand that in some cases, it isn't realistic to work with all the data for a particular event, in which case you can turn to sampling. You also learned what marketers mean when they talk about first, second, and third party data. 

And you know which tools marketing analysts use to collect data about online user behavior. You learned about browser cookies used to collect web browsing behavior data, pixels or tags to collect event data on specific websites, SDKs for data on app usage, and you learned how APIs are used to connect data from different sources to online platforms. 

And finally, you saw how Imra at Calla & Ivy uses all these tools to collect the data she needs for her marketing. Now, you know which data sources you can tap into for different data needs, and you know which tools to use to collect online data for different use cases. Given how many different data sources there are, knowing when different data collection tools apply is incredibly helpful. Now, you're ready to start looking into the tools you can use to categorize and analyze all that data. That's what's next. See you there!
