## Marketing Data Sources

### What Data do Marketers use

Marketing analytics can help you plan your marketing efforts, evaluate your effectiveness, and optimize your marketing and your purchase funnel, but none of that can be done without data. Data can come from different sources, can be of varying quality and can be helpful or unhelpful to you depending on what it is, but without data and the ability to understand and analyze it, marketing efforts can only go so far. 

As you know, all our online interactions generate data, but depending on the device you use to go online, the way data is collected differs. You may have heard of **cookies** and **pixels** used to track online behavior for instance. It's important to understand the mechanics of how this works as it will help you understand the nature of the digital data you're working with and the limitations. 

Then, we'll walk through an example of how a marketing team collects digital data and uses it for their campaigns. 


#### Data Related to Offline Behavior

Where does the data marketers use come from? Since we're such a digital world, you may think collecting data only happens online, and we'll talk about online data in our next video. But there's plenty of useful customer data that can be found offline too which can help give you a complete picture of who your customers are and how they behave. 

While the **customer journey** is shifting more and more online, there's still a significant part of that journey that happens in a physical location, whether it be a store purchase or engaging in a service. In fact, according to Statista, only 14.1% of retail sales in 2019 were made online, which means that 86% of customer purchases are happening in a physical location. 

Additionally, a report by Google shows that very few people do their purchasing wholly online or wholly offline, but use a mix of both. They either do research online and buy offline, or do research offline and buy online. This is why it's crucial to engage with both offline data and online data to truly understand customer behavior and use those insights to influence your marketing approach. 

What do we mean when we say offline data? It's simply data you gather about a customer that isn't through an online channel. This could be information collected through `a physical contact form`, signing up for a loyalty program, filling out a survey, or giving customer feedback. 

Offline data can also be tracked through point of sale information, when your customers make a purchase. You learn what product they bought, the date, any amount they spent. `Point of sales data` is often referred to as POS. Offline data can also include call center tracking or focus group participation as well. You can also track in-store visits and behavior through Wi-Fi logins, app usage in the store, and Beacons, which are little devices placed in the store that communicate with smartphones through Bluetooth signals. 

Let's look at an example of a bookstore. On a Wednesday afternoon, a customer stops by, browses around and comes to the counter with two bestsellers they want to purchase. The bookseller asks if they want to sign up for a frequent buyer card and the customer gives their name and address to the bookseller who enters them into their POS database. They also give their email address to sign up for the newsletter. The customer pays for their books and is on their way. This is the type of transaction that happens all the time. But now, the bookstore has all of this new data to help them better understand who's shopping at their store, not just a name but where their customer lives, their shopping habits, and sometimes age and gender.   

Offline data is typically rich with demographic information about customers, and it's often information that you may not be able to collect online. Offline data can also show how much each customer purchased, which can help determine their lifetime value, what they purchased, and when. The bookstore can now better understand its customer demographic, which will help with marketing efforts. 

The bookstore can also understand what times of the week are busiest, which will help them at staffing. It will also help them understand what inventory to keep in stock in order to increase sales. Now, because they have a name and email address attached to the purchase, they can target customers with book recommendations. And since they've collected this information directly from their customer, they can ensure that it's accurate and represents their current customer base. Since it was given directly to them, it mitigates any privacy concerns as well. 

All of the insights you can gather from this offline data can help you tailor your marketing strategy, better target your customer base, and see the context of your customers journey. But collecting offline data at point of sale isn't the only place where you can obtain it. Businesses can purchase third party data from companies who collect offline insights. This could include demographic information, purchasing behavior, and even information on offline media consumption that can help businesses gain further insights into their customers' behaviors.

You've probably heard of the `Nielsen TV` ratings or heard of someone who has a Nielsen box. Nielsen is a company that monitors media consumption across a variety of devices, including TVs and smartphones. `Comscore` is a similar company that also tracks media consumption across devices. This is another type of offline behavior. Businesses can then purchase their data to better understand customer behavior around media engagement, including when they watch and what they watch. 

`The better you can understand your customer, the better you can target them with advertising for your product or service.`

There are many other third party data sets you can buy. There are data from supermarket loyalty cards and credit card transactions, for instance, that provide information on the purchases of different products and brands. There are industry specific data like data for the pharmaceutical sector or data on car sales, etcetera. 

While most brands have access to their own sales data, these third party datasets help them with competitive analysis as they give them some insights into the sales for other brands as well.


#### Data Related to Online Behavior

With society today becoming more and more digital, marketers have a vast number of tools they can use that will help them gain insights from **customers' online behavior.** Those insights can better inform marketing efforts, `make advertising more personalized`, and engagement more meaningful. 

Here are some of the ways that marketers can track customers as they move through their journey to a purchase.

Brand engagement may begin by interacting with a brand's content or posts on social media for instance. Platforms like Facebook, Instagram, and Twitter have insights or analytics dashboards that can reveal a lot about an account's followers, including the number of followers, where they're from, what their age is, their gender breakdown, when they're most frequently online, and what languages they speak. This can help a business understand who their audience is on social media, and if the audience they're targeting is indeed the one following them. Social media insights can also provide information on which pieces of content are being interacted with the most, which is also helpful knowledge about your audience. 

User engagement may also begin when someone sees an ad on social media for a product or service you offer. This is different from the kind of organic engagement a business would build with original content in the way of posts and videos. Instead, the business would create ads targeted to a specific audience with specific characteristics and demographics. When someone clicks on the ad, the business can track the interaction and further interactions with business. 

Businesses who created ad campaigns through a platform like Facebook Ads Manager, can see when people interact with their ad and what consumers do as a result of seeing the ad. Do they visit a website or app, sign up on the email list or buy a product or service? This data, so knowing whether an ad campaign results in a full purchase or just a website visit, is incredibly valuable to have in order to better understand the impact of your marketing efforts. 

Website insights produced by dashboards like `Google Analytics` or `Adobe Analytics`, are also able to give you a lot of rich audience data that you can use to inform your marketing strategies. Similar to social media insights, website analytics will tell you how many people are visiting your site, where they're from, what language they speak, their age, and their gender breakdown. It will also tell you where they're entering or leaving your site, how long they're staying on your site, and which pages they're drawn to the most. You can use website data to see how well you're doing on `website engagement,` content areas to fix, and if your efforts to drive your audience to your site are working. 

Keep in mind that these insights from social media dashboards and Google Analytics are going to be anonymous to you. You'll know, for example, that 1,000 people between the ages of 30 and 40 living in New York City, clicked on your ad, but you won't know who they are. 

If you sell products online, you can track not only purchases, but names and information of your customers, like the point of sales data collection we saw in the last video. Here's an overview dashboard from Shopify, a popular e-commerce software tool. Purchasing information will give you a lot of demographic data, product preference data, and customer purchasing behavior insights to use for your future strategies. 

You could also, more actively, collect customer information through something as simple as a sign-up form for a newsletter, a free e-book, or a rewards or loyalty program. 

Or you can also gather customer information through feedback questionnaires and surveys that can give you insights on how a customer feels about your brand, uses your products, or how likely they would be to recommend you to others.   

So far we've talked about data that can be gathered **online** for a specific website, app, or online business. However, there are instances where marketers want to collect information about the competition as well. They may want to know what audience a competitor attracts, or they may want to get more insights into how they stack up versus the competition. 
  
Marketers can leverage third-party databases to gather data about competitors. These third-party databases provide data collected and reported by someone else, namely a third party. 

In most cases, marketers will have to pay for that data. As with offline data, there are many third-party databases available related to online behavior. Marketers use tools that provide data on online browsing behavior, as well as data gathered from social media posts. **Comscore** and **Nielsen** are two prominent providers of data on online behavior. Both report on which websites and apps people use, how much time they spend on them, the demographics of the people who use them, and so on. Together with their data on offline media usage, they provide marketers with a good picture of how users spend their media time. 

Another type of data tools that can be useful to marketers are social listening tools. They can help marketers understand what people outside their audience are saying about their brand online. They monitor how often different brands are mentioned in social media posts and they provide insights on whether these mentions are mostly positive or negative. As with any type of data you collect, the impact on your marketing strategy and overall revenue generation and brand awareness doesn't come from simply collecting the data. It comes from analyzing it, gaining insights in what it's saying and using those insights to inform your future strategy. 


#### Sampled or non-Sampled Data

Learn what types of data are going to be useful to your business, what your best methods are for tracking data, how to interpret data points to provide you with insights and how to interpret raw data. One more item to be aware of is understanding if you want to use sampled or unsampled data. 

Sampled data is exactly what it sounds like, a sample or selection of the larger data set that represents the whole of the data set. Why would you use sampled data? If you want to get insights about your customers, you'd ideally want to ask all of them, but often that's not possible. So, you may take a sample of your customer base knowing that their insights and feedback will represent the whole. 

For example, a movie theater launches a new self service kiosk for tickets and 1000 people use it on the first day. The manager wants to get a sense of how the experience went, but it's too big of a job to talk to all 1000 people who used the Kiosk. What the manager would do is talk to a few users, or a sample, to get their feedback. The movie theater would get the data and insights they want from the sample without needing to ask every single person. From the sample, the movie theater is able to make inferences on how to leverage and promote the new self service kiosk. 

Here's another example: do you remember the media consumption data from Nielsen we refer to in an earlier video? This is a good example of a data set that uses sampling. To monitor people's tv viewing habits, Nielsen recruits households whose tv viewing behavior it will monitor. These people agree to be monitored and they also fill out a questionnaire that provides Nielsen with demographic and interest data. Nielsen then uses the information they gather from those households to build a data set that represents the total population. 

You may also use sampling when your data set is too large to handle, which would slow down generating any insights. Using a sample of the data would give you a more manageable data set with faster analysis time. And since the sample represents the whole, it should give you the same insights. 

For example, a marketer collects customer data but finds that they have thousands and thousands of entries to analyze. Working with that many pieces of data will take a lot of time and effort yet pulling out a sample of that data, only 1000 entries or a few 100 for instance, would give the same insights, just at a smaller scale, and would be much easier to work with.

Marketers use this tool to monitor people's browsing behavior on their website or app. If you use Google Analytics on a very large website that is visited by many people, then Google Analytics will use sampling, so it can give you access to your data and reports faster.

What is non sampled data? Well, it's simply the whole population or data set in its raw state and there are certainly times when you use the entire population for your analysis purposes. For instance, if you're looking for events that don't occur frequently, a sample may not be a good way to go as you may not catch the event you were looking for, if you only look at a small selection of data. 

You probably noticed when I talk about sampled data that I refer to the sample as a data selection that represents the total data set. It means that we assume that the characteristics of the sample are the same as the characteristics of my total data set. And thus it's okay to look at the sample and draw conclusions about the total data set. 

There are a few different methods you can use to get a representative sample. We will take a closer look at them later in this program when we dive into statistics. For now, I will just mention the most common method: **random sampling**, which simply involves picking members or entries at random. This can be done using a random number generator and gives everyone a fair chance of being chosen.

**Selecting a representative sample is important.** Let's go back to our movie theater example and their self service kiosk. If I want to know what people think of the self service kiosk experience and I plan to take a sample of 20 people, it's not a great idea to select the first 20 people in line. By doing that, I may, for instance, pick only families with kids who are catching the morning show of a Disney movie. The self service experience may be different for them than for the crowd that shows up later at night to see a romantic comedy. By randomly selecting 20 people throughout the entire day, I have a better chance of selecting a group that represents the full spectrum of theater visitors.


#### First party - Second Party - Third party Data

The different types and quality of data you may use as a marketer or analyst, as determined by how you collect it. If you ever had to write a report for school that involved research, you know that using primary sources like journals or firsthand accounts were always the best sources to use, because they got you the closest to what actually happened. Secondary or tertiary sources were fine, but weren't as factual, or helpful as primary sources. The same is true when you're working with first-party, second-party, and third-party data. 

Not all data is equally as useful or helpful. So it's important to know the difference between the three, how you obtained each, and when you would use each one to help in your marketing efforts.

We'll start with first-party data, since that type of data is going to be the most valuable and relevant to you. First-party data is simply data you've collected about your customers directly from your customers.

  * Rewards sign up   
  * Unique visitors   
  * Newsletter interests   
  * Ad click   
  * Purchase data   
  
  This can be through the offline and online sources we mentioned in previous videos, like tracking site visits, social media follows, or via sign up in store. Examples of first-party data could be the name and address of a customer who signs up for a rewards card at a store location. The amount of unique visitors your homepage received last year, the information a customer fills in about their interests when they fill out a newsletter sign-up form. The average age of Facebook users who clicked on one of your ads, or the customers who purchased a specific item last month. 
  
  Because first-party data directly reflects your audience or customer base, it will show you customers' behavior and actions, purchase history, and how your audience engages with your brand. This kind of information can help you plan campaigns and new strategies, and continue deepening the relationship with your current audience. Additionally, because first-party data is data directly collected from your customers, you know that it's going to be accurate, and provide a lot of rich insights. 
  
  But one of the drawbacks is that it's only *limited to your audience*, so you aren't necessarily getting insights from potential audiences, or able to engage with new customers. 
  
  Still, first-party data is going to be the most useful to you, and the most accurate representation of your audience. 
  
  Second-party data is essentially second hand data, or data you did not collect yourself. Think of it as another businesses' first-party data that they're sharing with you. Or, if you share your first-party data with another business, that would be their second-party data. Why would businesses willingly share data with one another? If two businesses cater to a similar demographic or audience, they may partner in sharing their data, which may give insights into potential new audiences or trends. 
  
  For example, there's a coffee shop on one block, and a bakery on the next block, and the owners are friends. The coffee shop only focuses on coffee, no baked goods. But sometimes, people come in with bags from the bakery. Similarly, the bakery just focuses on baked goods, and doesn't want to branch into coffee. But they often see customers come in with cups from the coffee shop. Even though there is some overlap, there are still bakery customers that may not yet have tried the coffee shop, but may enjoy it. And there are coffee shop customers that may not yet have tried the bakery. The businesses then share their first-party data with each other, so that each business can now target more people who may be interested in their products, and bringing more new customers.
  
  Businesses may also choose to purchase second-party data they believe could help them in their marketing efforts. This approach is certainly easier, but unless you're able to preview the data first, you may not be getting a hold of useful data for your business. You may also run into privacy issues, based on how the data was originally collected. 
  
  Finally, third-party data is collected not by you or another business you partnered with, but by a third party not directly linked to the end customer. That data is then sold to businesses who can use it to expand their targeting efforts. Third-party data is collected using similar approaches to first-party data, like through customer surveys, feedback, or tracking of online behavior. 
  
  But the data is typically collected through random sampling. In other words, it won't be your particular audience, but across the general population. For example, a new restaurant opens in a neighborhood, and they want to target an audience within a specific zip code. They may buy data about everyone within that particular area. They, of course, wouldn't know if the population on the list would even like their restaurant, or be in their target audience. But they can use the data to do an all encompassing campaign, or add the data to their current customer data to increase their reach.
  
  When you buy third-party data, you may not have as much insight into how the data was collected. And the data may be incomplete, or of lower quality than first-party data. 
  
  Additionally, any organization can purchase the data, so it wouldn't be uniquely yours. There may also be further privacy risk around how third-party data was collected as well. While third-party data may not be the primary data set a marketer uses, third-party data can be useful to round out first or second-party data, or for comparison. 
  
  So acquiring third-party data may be worth it. What data will be best for you? You will probably find reasons to use all three in your marketing efforts and planning. But it's going to be best to emphasize first-party data, since that will give you the most accurate reflection of who your customers are, and provide you the most accurate insight into their behaviors.

